### ISSUE TITLE
Can't use pico-fido-tool.py backup function PIN_AUTH_INVALID

### ISSUE THREAD

**Issue by M11158002** [polhenarejos/pico-fido#22]
When I use the backup function of pico-fido-tool.py, I get fido2.ctap.CtapError: CTAP error: 0x33 - PIN_AUTH_INVALID error.

Execution environment:
Git Branch: development
System Version: Ubuntu 22.04.3 LTS
Architecture: amd64
Python Version:3.11.6
Python package:
fido2:1.1.2
keyring:24.2.0
cryptography:41.0.5

**Comment by polhenarejos** [comment]
Fixed in 421bea64.

`pico-fido-tool.py` has been upgraded to v1.5, which adds support for `-p/--pin`.

To backup:
1. First enable security: `python3 pico-fido-tool.py --pin 123456 secure enable`.
2. Second unlock the device: `python3 pico-fido-tool.py --pin 123456 secure unlock`.
3. Third backup the device: `python3 pico-fido-tool.py --pin 123456 backup save file.backup`.

Note that if you enable `secure`, the device is tied to your computer and it cannot be used in anywhere else. Also, you must `secure unlock` on every plug in. To disable, `secure disable`.
