### ISSUE TITLE
support PIV Card

### ISSUE THREAD

**Issue by ghost** [polhenarejos/pico-fido#80]
would be nice to combine this with https://github.com/polhenarejos/pico-hsm

**Comment by polhenarejos** [comment]
PIV is supported by Pico OpenPGP.

**Comment by polhenarejos** [comment]
There are several reasons:
1. I do not think having a single key for multiple purposes is the best choice. It might make sense if the key is expensive or enterprise. But when we talk about cheap keys, I think it is better to isolate different stacks. Imagine that there's a bad implementation in some stack or it has a security flaw. It may affect to the other keys.
2. Sandboxing an application is not straightforward. The simplest solution is mixing all stacks and security material to optimize the physical space. But then, when we reset an application, all keys from other apps are also wiped too. On the contrary, if you sandbox each application, then you are wasting resources and space, which is very limited. 
3. There are some collisions in the files used by multiple apps. For instance, HSM and OpenPGP define some directives that are shared by both. We can override some of them by adding an extra layer in the middle to remap virtual and physical addressing, but it is an extra effort for no clear reason.
4. There can be hardware incompatibilities at OS level. CCID is known to lock exclusively the boards and it depends on the software you use and the OS. FIDO has not this drawback, but it may bring some problems to specific users.
5. These projects started in parallel and in order to minimize implementation problems, I preferred to make a common SDK and then, specific applications (HSM, FIDO, OTP, OpenPGP, etc.) separately.
6. The interests are not usually shared by the community. Usually who is interested in FIDO keys is not interested in OpenPGP or HSM. And viceversa. Putting together may bring additional boilerplate capabilities to the users not interested in all features.
7. I want to split applications as much as possible for compatibilities issues. The best way to do it is by doing it at physical level.

Perhaps some day I will unify all these products but it is not in the short term horizon.
